In [9]:
import tensorflow as tf
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
a = tf.constant(1)
print(a)
b = tf.constant(1.0)
print(b)
c = tf.constant(2.3, dtype=tf.double)
print(c)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(2.3, shape=(), dtype=float64)


In [5]:
a = tf.ones((3, 4))
print(a)
print(a.ndim)
print(a.shape)
print(tf.is_tensor(a))
print(a.dtype)
print(a.name)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)
2
(3, 4)
True
<dtype: 'float32'>


AttributeError: Tensor.name is meaningless when eager execution is enabled.

In [4]:
a = tf.convert_to_tensor(np.arange(10))
b = tf.Variable(a)
print(b)
print(tf.is_tensor(b))
print(isinstance(b, tf.Tensor))

<tf.Variable 'Variable:0' shape=(10,) dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>
True
False


In [5]:
print(tf.convert_to_tensor(np.ones([2, 3])))
print(tf.convert_to_tensor(np.zeros([2, 3])))
print(tf.convert_to_tensor([1, 2]))
print(tf.convert_to_tensor([[2], [3.]]))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float64)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float64)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[2.]
 [3.]], shape=(2, 1), dtype=float32)


In [6]:
print(tf.zeros([]))
print(tf.zeros([1]))
print(tf.zeros([2, 2, 2]))

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor([0.], shape=(1,), dtype=float32)
tf.Tensor(
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]], shape=(2, 2, 2), dtype=float32)


In [7]:
a = tf.zeros([2, 3, 4])
print(tf.zeros_like(a))

tf.Tensor(
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]], shape=(2, 3, 4), dtype=float32)


In [9]:
print(tf.random.normal([2, 2], mean=1, stddev=1))
print(tf.random.truncated_normal([2, 2], mean=1, stddev=1))

tf.Tensor(
[[-0.68817353 -0.02452338]
 [ 1.8423855  -0.07827806]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.5679045   0.07777387]
 [ 1.1313475  -0.08814859]], shape=(2, 2), dtype=float32)


In [11]:
print(tf.random.uniform([2, 2], minval=0, maxval=1))
print(tf.random.uniform([2, 2], minval=0, maxval=1, dtype=float))

tf.Tensor(
[[0.9859315  0.93620193]
 [0.12326717 0.85342634]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.92849565 0.90404665]
 [0.03953874 0.64431083]], shape=(2, 2), dtype=float32)


In [15]:
print(tf.range(10))
print(tf.range(10, 100, delta=3, dtype=tf.int32))

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor(
[10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70 73 76 79
 82 85 88 91 94 97], shape=(30,), dtype=int32)


In [19]:
array = tf.random.uniform([3, 4, 5, 6], maxval=100, dtype=tf.int32)
print(array[0][0])
print(array[0][0][1])
print(array[0][0][1][-1])  # 负号下标表示逆向索引

tf.Tensor(
[[95 65 47 29  9 47]
 [39 69 77 42 94 80]
 [76 94 59 92 84  3]
 [59 27  8 29 65 70]
 [79 32 80 14  7 20]], shape=(5, 6), dtype=int32)
tf.Tensor([39 69 77 42 94 80], shape=(6,), dtype=int32)
tf.Tensor(80, shape=(), dtype=int32)


In [20]:
array = tf.random.uniform([3, 4, 5, 6], maxval=100, dtype=tf.int32)
print(array[0, 0])
print(array[0, 0, 1])
print(array[0, 0, 1, -1])  # 负号下标表示逆向索引

tf.Tensor(
[[28  2  1  5 26 85]
 [62 41 19 67 17 29]
 [17 18 38 30 89 11]
 [79 96 72 87 77 63]
 [33 74 62 51 58 42]], shape=(5, 6), dtype=int32)
tf.Tensor([62 41 19 67 17 29], shape=(6,), dtype=int32)
tf.Tensor(29, shape=(), dtype=int32)


In [2]:
array = tf.random.uniform([2, 3])
print(array[:, :].shape)
print(array[:, 0].shape)
print(array[:, ::2].shape)
print(array[:-1, :].shape)

print(array[:].shape)
print(array[:, ...].shape)
print(array[::, ::].shape)

(2, 3)
(2,)
(2, 2)
(1, 3)
(2, 3)
(2, 3)
(2, 3)


In [10]:
a = tf.random.uniform([4, 35, 3])
print(tf.gather(a, axis=0, indices=[0, 1, 3]).shape)
print(tf.gather_nd(a, [[0, 1, 2], [1, 2, 0]]).shape)
print(tf.boolean_mask(a, mask=[True, True, False, False], axis=0).shape)

(3, 35, 3)
(2,)
(2, 35, 3)


In [14]:
a = tf.random.uniform([16, 28, 28, 3])
print(a.shape, ' ', a.ndim)
print(tf.reshape(a, [16, 28*28, 3]).shape)
print(tf.reshape(a, [16, -1, 3]).shape)
print(tf.reshape(a, [16, 28*28*3]).shape)
print(tf.reshape(a, [16, -1]).shape)


(16, 28, 28, 3)   4
(16, 784, 3)
(16, 784, 3)
(16, 2352)
(16, 2352)


In [15]:
a = tf.random.uniform([16, 28, 28, 3])
print(tf.transpose(a, [0, 3, 1, 2]).shape)

(16, 3, 28, 28)


In [16]:
a = tf.random.normal([4, 35, 8])
print(tf.expand_dims(a, axis=0).shape)
print(tf.expand_dims(a, axis=3).shape)

(1, 4, 35, 8)
(4, 35, 8, 1)


In [17]:
a = tf.random.normal([1, 28, 28, 1])
print(tf.squeeze(a, axis=0).shape)
print(tf.squeeze(a, axis=3).shape)
print(tf.squeeze(a, axis=-1).shape)

(28, 28, 1)
(1, 28, 28)
(1, 28, 28)


In [20]:
a = tf.random.normal([4, 32, 32, 3])
b = tf.random.normal([3])
c = tf.random.normal([2, 1, 1, 1])
print((a+b).shape)
print((a+c).shape)

(4, 32, 32, 3)


InvalidArgumentError: Incompatible shapes: [4,32,32,3] vs. [2,1,1,1] [Op:AddV2] name: add/

In [26]:
a = tf.ones([2, 2])
b = tf.fill([2, 2], 1.)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)
print(tf.math.log(a))

tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


In [27]:
a = tf.random.normal([2, 3])
b = tf.random.normal([3, 4])
print(a@b)
print(tf.matmul(a, b))

tf.Tensor(
[[ 0.21384473 -3.0221746  -0.53907126 -0.4756937 ]
 [ 1.9671813   0.23523177  0.6544778  -2.3652413 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[ 0.21384473 -3.0221746  -0.53907126 -0.4756937 ]
 [ 1.9671813   0.23523177  0.6544778  -2.3652413 ]], shape=(2, 4), dtype=float32)


In [28]:
a = tf.random.normal([2, 3, 4])
print(tf.reduce_mean(a, axis=0))
print(tf.reduce_sum(a, axis=2))

tf.Tensor(
[[ 1.7585342e-01  5.4030526e-01  7.2788095e-01 -1.1683108e-01]
 [ 2.4512267e-01  2.5665331e-01  6.5582943e-01  5.1557487e-01]
 [-7.6059538e-01  9.5709264e-03 -4.9916510e-02 -3.8948376e-04]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[-0.637954    0.9183196  -0.92917573]
 [ 3.292371    2.4280412  -0.6734851 ]], shape=(2, 3), dtype=float32)
