In [1]:
import tensorflow as tf

In [4]:
a = tf.ones([4, 35, 8])
b = tf.ones([2, 35, 8])
c = tf.concat([a, b], axis=0)
print(c.shape)
a = tf.ones([4, 32, 8])
b = tf.ones([4, 3, 8])
c = tf.concat([a, b], axis=1)
print(c.shape)

(6, 35, 8)
(4, 35, 8)


In [7]:
a = tf.ones([4, 35, 8])
b = tf.ones([4, 35, 8])
c = tf.stack([a, b], axis=0)
print(c.shape)
c = tf.stack([a, b], axis=3)
print(c.shape)

(2, 4, 35, 8)
(4, 35, 8, 2)


In [8]:
a = tf.ones([4, 35, 8])
b = tf.ones([4, 35, 8])
c = tf.stack([a, b], axis=0)
aa, bb = tf.unstack(c, axis=0)
print(aa.shape, bb.shape)
res = tf.unstack(c, axis=3)
print(res[0].shape, res[6].shape)

(4, 35, 8) (4, 35, 8)
(2, 4, 35) (2, 4, 35)


In [10]:
a = tf.ones([4, 35, 8])
b = tf.ones([4, 35, 8])
c = tf.stack([a, b], axis=0)
print(c.shape)
res = tf.split(c, axis=3, num_or_size_splits=2)
print(len(res))
res = tf.split(c, axis=3, num_or_size_splits=[2, 2, 4])
print(len(res))
print(res[0].shape, res[2].shape)

(2, 4, 35, 8)
2
3
(2, 4, 35, 2) (2, 4, 35, 4)


In [11]:
a = tf.ones([2, 2])
print(tf.norm(a))
print(tf.sqrt(tf.reduce_sum(tf.square(a))))
print(tf.norm(a, axis=1))

print(tf.norm(a, ord=1, axis=0))

tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor([1.4142135 1.4142135], shape=(2,), dtype=float32)
tf.Tensor([2. 2.], shape=(2,), dtype=float32)


In [16]:
a = tf.random.normal([4, 10])
tf.reduce_min(a), tf.reduce_max(a), tf.reduce_mean(a)
tf.reduce_min(a, axis=1), tf.reduce_max(a, axis=1), tf.reduce_mean(a, axis=1)

(<tf.Tensor: id=213, shape=(), dtype=float32, numpy=-2.2308245>,
 <tf.Tensor: id=215, shape=(), dtype=float32, numpy=2.4059465>,
 <tf.Tensor: id=217, shape=(), dtype=float32, numpy=0.06347918>,
 <tf.Tensor: id=219, shape=(4,), dtype=float32, numpy=array([-0.12330155, -2.2308245 , -1.9824525 , -0.8308944 ], dtype=float32)>,
 <tf.Tensor: id=221, shape=(4,), dtype=float32, numpy=array([2.4059465, 1.4869152, 1.687304 , 2.1147592], dtype=float32)>,
 <tf.Tensor: id=223, shape=(4,), dtype=float32, numpy=array([ 0.85363805, -0.71917427, -0.04644271,  0.16589561], dtype=float32)>)

In [17]:
a = tf.random.normal([4, 10])
print(tf.argmax(a))
print(tf.argmax(a, axis=0))

tf.Tensor([0 1 0 1 2 2 1 1 1 3], shape=(10,), dtype=int64)
tf.Tensor([0 1 0 1 2 2 1 1 1 3], shape=(10,), dtype=int64)


In [19]:
a = tf.convert_to_tensor([0, 1, 2, 3, 6])
b = tf.range(5)
res = tf.equal(a, b)
print(res)
print(tf.reduce_sum(tf.cast(res, tf.int32)))

tf.Tensor([ True  True  True  True False], shape=(5,), dtype=bool)
tf.Tensor(4, shape=(), dtype=int32)


In [20]:
a = tf.convert_to_tensor([2, 3, 2, 4, 4, 5])
print(tf.unique(a))

Unique(y=<tf.Tensor: id=250, shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5])>, idx=<tf.Tensor: id=251, shape=(6,), dtype=int32, numpy=array([0, 1, 0, 2, 2, 3])>)


In [22]:
a = tf.random.shuffle(tf.range(5))
print(a)
print(tf.sort(a, direction='DESCENDING'))
idx = tf.argsort(a, direction='DESCENDING')
tf.gather(a, idx)

tf.Tensor([2 0 1 3 4], shape=(5,), dtype=int32)
tf.Tensor([4 3 2 1 0], shape=(5,), dtype=int32)


<tf.Tensor: id=281, shape=(5,), dtype=int32, numpy=array([4, 3, 2, 1, 0])>

In [27]:
a = tf.convert_to_tensor([1, 2, 3, 4, 4, 5])
print(a)
res =  tf.math.top_k(a, k=2)
print(res.values)
print(res.indices)

tf.Tensor([1 2 3 4 4 5], shape=(6,), dtype=int32)
tf.Tensor([5 4], shape=(2,), dtype=int32)
tf.Tensor([5 3], shape=(2,), dtype=int32)


In [29]:
a = tf.reshape(tf.range(9), [3, 3])
print(tf.pad(a, [[0, 0], [0, 0]]))
print(tf.pad(a, [[1, 0], [1, 1]]))
print(tf.pad(a, [[1, 1], [1, 1]]))

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 0 0 0 0]
 [0 0 1 2 0]
 [0 3 4 5 0]
 [0 6 7 8 0]], shape=(4, 5), dtype=int32)
tf.Tensor(
[[0 0 0 0 0]
 [0 0 1 2 0]
 [0 3 4 5 0]
 [0 6 7 8 0]
 [0 0 0 0 0]], shape=(5, 5), dtype=int32)


In [32]:
a = tf.reshape(tf.range(4), [2, 2])
print(a)
print(tf.tile(a, multiples=[1, 3]))
print(tf.tile(a, [2, 2]))

tf.Tensor(
[[0 1]
 [2 3]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0 1 0 1 0 1]
 [2 3 2 3 2 3]], shape=(2, 6), dtype=int32)
tf.Tensor(
[[0 1 0 1]
 [2 3 2 3]
 [0 1 0 1]
 [2 3 2 3]], shape=(4, 4), dtype=int32)


In [35]:
a = tf.range(10)
print(a)
print(tf.maximum(a, 2))
print(tf.minimum(a, 2))

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor([2 2 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor([0 1 2 2 2 2 2 2 2 2], shape=(10,), dtype=int32)


In [36]:
a = tf.range(10)
print(tf.clip_by_value(a, 2, 8))

tf.Tensor([2 2 2 3 4 5 6 7 8 8], shape=(10,), dtype=int32)


In [37]:
a = tf.random.normal([2, 2], mean=10)
print(tf.norm(a))
aa = tf.clip_by_norm(a, 15)
tf.norm(aa)

tf.Tensor(18.948463, shape=(), dtype=float32)


<tf.Tensor: id=416, shape=(), dtype=float32, numpy=15.0>

In [40]:
a = tf.random.normal([3, 3])
mask = a > 0
print(mask)
print(tf.boolean_mask(a, mask))
indices = tf.where(mask)
print(tf.gather_nd(a, indices))

tf.Tensor(
[[ True  True False]
 [False False False]
 [ True  True  True]], shape=(3, 3), dtype=bool)
tf.Tensor([0.36952588 0.2789304  0.3798391  0.32346752 0.3061909 ], shape=(5,), dtype=float32)
tf.Tensor([0.36952588 0.2789304  0.3798391  0.32346752 0.3061909 ], shape=(5,), dtype=float32)


In [42]:
indices = tf.constant([[4], [3], [1], [7]])
updates = tf.constant([9, 10, 11, 12])
shape = tf.constant([8])
print(tf.scatter_nd(indices, updates, shape))

tf.Tensor([ 0 11  0 10  9  0  0 12], shape=(8,), dtype=int32)


In [50]:
x, y = tf.linspace(-2., 2, 5), tf.linspace(-2., 2, 5)
x_points, y_points = tf.meshgrid(x, y)
print(x_points)
print(y_points)
print(tf.stack([x_points, y_points], axis=-1)[:1,...])

tf.Tensor(
[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]], shape=(5, 5), dtype=float32)
tf.Tensor(
[[-2. -2. -2. -2. -2.]
 [-1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.]], shape=(5, 5), dtype=float32)
tf.Tensor(
[[[-2. -2.]
  [-1. -2.]
  [ 0. -2.]
  [ 1. -2.]
  [ 2. -2.]]], shape=(1, 5, 2), dtype=float32)
